### ISSUE TITLE
How to drag this plan box, stretch, shorten, and move.

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#10]
![image](https://user-images.githubusercontent.com/34624856/51897721-582a5700-23ea-11e9-97fd-792e3bbe8b2f.png)
![image](https://user-images.githubusercontent.com/34624856/51897769-72643500-23ea-11e9-993e-93183c6747c5.png)
![image](https://user-images.githubusercontent.com/34624856/51897786-8019ba80-23ea-11e9-83a7-bb9c33cd8e98.png)

**Comment by sohee-lee7** [comment]
@xiaomao996688  If you use `beforeUpdateSchedule` event, you could get information moved schedule and then should update the schedule of `scheduleList`.
```js
@beforeUpdateSchedule="onBeforeUpdateSchedule"
```

**Comment by xiaomao996688** [comment]
> `beforeUpdateSchedule` event

In the beforeUpdateSchedule event, I didn't get the moved information.

**Comment by xiaomao996688** [comment]
![image](https://user-images.githubusercontent.com/34624856/52022414-c169b180-2533-11e9-9295-7c4f0307e22f.png)
![image](https://user-images.githubusercontent.com/34624856/52022425-c9c1ec80-2533-11e9-84b8-b08f6426091e.png)
