### ISSUE TITLE
I got location-related information through this API. But I don't know how to set this up to move and stretch.

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#12]
![image](https://user-images.githubusercontent.com/34624856/52024055-57083f80-253a-11e9-84a0-403c3b61b830.png)
![image](https://user-images.githubusercontent.com/34624856/52024256-2674d580-253b-11e9-82cd-d224ee7ea353.png)

**Comment by dongsik-yoo** [comment]
I think you need to provide more specific information, what you want to do, what's the problem you really have. If you want edit a schedule you click, you can edit it on a edit popup. If you want to move it, you just drag it!

**Comment by xiaomao996688** [comment]
> I think you need to provide more specific information, what you want to do, what's the problem you really have. If you want edit a schedule you click, you can edit it on a edit popup. If you want to move it, you just drag it!

I want to drag the plan box, and I can stretch the size of this plan box, but I don't know which method to use.

**Comment by xiaomao996688** [comment]
![image](https://user-images.githubusercontent.com/34624856/52678648-5bd2e780-2f6d-11e9-8a1c-e4bc47caf4f1.png)
How to drag and stretch this task.

**Comment by xiaomao996688** [comment]
This problem has been solved and can be closed.
