### ISSUE TITLE
display the month picker

### ISSUE THREAD

**Issue by nazihheni** [nhnent/toast-ui.vue-calendar#13]
## Current Behavior

please any one can tell me  how to enbale the month changer ?
```js
// Write example code
```
![screenshot_2019-02-06 tutorial example01-basic calendar](https://user-images.githubusercontent.com/9407523/52376284-ad401b80-2a2f-11e9-816d-d48a96852126.png)

**Comment by jungeun-cho** [comment]
@nazihheni 
Click the left and right arrow buttons to change the month.

**Comment by haringsrob** [comment]
Hi @jungeun-cho,

I think he means the arrows etc (what is in the black drawing) is simply not appearing.

I am looking for a solution myself.

Kind regards,

**Comment by jungeun-cho** [comment]
@haringsrob 
Do you want to know the API used to change the month?
We support movable api.

https://nhn.github.io/tui.calendar/latest/Calendar#setDate
https://nhn.github.io/tui.calendar/latest/Calendar#prev
https://nhn.github.io/tui.calendar/latest/Calendar#next
https://nhn.github.io/tui.calendar/latest/Calendar#today

e.g.)
```js
<calendar ref="tuiCalendar" style="height: 800px;"
...
>
this.$refs.tuiCalendar.invoke('setDate', new Date(e.date));
this.$refs.tuiCalendar.invoke('changeView', 'month', true);  // 'month', 'week' or 'day'
```
