### ISSUE TITLE
Customize Popup Create Event

### ISSUE THREAD

**Issue by luizotavior** [nhnent/toast-ui.vue-calendar#14]
Hello, I'm having trouble customizing the popup that creates the calendar.

I took a look at the Template options however I did not find the option to modify the creation popup (Not the popupDetail).

Is there any way I can customize this part?

![https://screenshotscdn.firefoxusercontent.com/images/16ec0726-1bb9-422a-8e13-f662d276e0e3.png](https://screenshotscdn.firefoxusercontent.com/images/16ec0726-1bb9-422a-8e13-f662d276e0e3.png)

Thank you for your attention.
Congratulations on the Library, I really enjoyed it!

**Comment by dongsik-yoo** [comment]
@luizotavior I appreciate you enjoy TOAST UI Calendar!
There is no option for customizing the popup. It's for users who want to simply use this calendar. I make own creation popup on my service.

**Comment by luizotavior** [comment]
Ok thank you.
