### ISSUE TITLE
How to drag and stretch this tasks.

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#15]
![image](https://user-images.githubusercontent.com/34624856/52680669-42816980-2f74-11e9-9616-232266204e15.png)
Which method should be used？

**Comment by dongsik-yoo** [comment]
Use the mouse or see [updateSchedule](https://nhnent.github.io/tui.calendar/latest/Calendar.html#updateSchedule) function for programmatically updating a event.

**Comment by xiaomao996688** [comment]
> Use the mouse or see [updateSchedule](https://nhnent.github.io/tui.calendar/latest/Calendar.html#updateSchedule) function for programmatically updating a event.

![image](https://user-images.githubusercontent.com/34624856/52686049-0a375680-2f87-11e9-8618-f2c473b1d878.png)
Which property controls dragging?
Which property controls stretching?
![image](https://user-images.githubusercontent.com/34624856/52686093-3f43a900-2f87-11e9-8a4e-9ea00dcad107.png)

**Comment by dongsik-yoo** [comment]
Modify `start` and `end` to drag.
Modify `end` to stretch it.
Thank you.

**Comment by xiaomao996688** [comment]
> Modify `start` and `end` to drag.
> Modify `end` to stretch it.
> Thank you.
How do I get e.schedule.end and e.schedule.start after clicking Stretch?
![image](https://user-images.githubusercontent.com/34624856/52689904-d06e4c00-2f96-11e9-94a6-f3b75c6b38a5.png)

**Comment by dongsik-yoo** [comment]
Please see the API document.
https://nhnent.github.io/tui.calendar/latest/Calendar.html#event:beforeUpdateSchedule

**Comment by xiaomao996688** [comment]
> Please see the API document.
> https://nhnent.github.io/tui.calendar/latest/Calendar.html#event:beforeUpdateSchedule
thank you for helping me,
thanks for your guidance.

**Comment by dongsik-yoo** [comment]
If you have any question or another issue, please make a new issue. I close this.
Thank you.
