### ISSUE TITLE
Upgrade to TUI 1.10.0

### ISSUE THREAD

**Issue by Phantom75** [nhnent/toast-ui.vue-calendar#16]
## Version
1.0.3
## Test Environment
MacOSX - Firefox

## Current Behavior
In firefox it's not possible to create new entries due to a defect in toast UI itself that has been fixed in the latest version of TUI (1.10.0)

## Expected Behavior
Could you please reference to the latest Toast-UI version so it becomes usable again for FF? Thanks a lot!

**Comment by jungeun-cho** [comment]
@Phantom75 
If the schedule is urgent, install the latest version of the tui calendar on your project.
```sh
$ npm i tui-calendar@latest
```

I'll update the package.json file. :-)
