### ISSUE TITLE
How to switch between 12 and 24 hour clock?

### ISSUE THREAD

**Issue by kcurbel** [nhnent/toast-ui.vue-calendar#5]
## Version

@toast-ui/vue-calendar@1.0.3
│ └── tui-calendar@1.9.0
vue@2.5.17
## Current Behavior
I would like to change between military(24 hour) and 12 hour clock on the calendar grid. There seems to be no documentation regarding it on the main website. https://nhnent.github.io/tui.calendar/latest/Calendar.html#toggleScheduleView

**Comment by sohee-lee7** [comment]
@kcurbel I'm sorry to have to answer late. We doesn't support 12 hour clock. If you mean just show 12 hour clock in time view, you could reference https://github.com/nhnent/tui.calendar/issues/171.
