### ISSUE TITLE
sorry I find “npm install” error。

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#7]
## Current Behavior

```js
// Write example code
```

**Comment by xiaomao996688** [comment]
eslint-config-tui\rules\style.js:
	Configuration for rule "padding-line-between-statements" is invalid:
	Value "iife" should be equal to one of the allowed values.
	Value "iife" should be array.
	Value "iife" should match some schema in anyOf.

**Comment by sohee-lee7** [comment]
@xiaomao996688 This issue resolved??
