### ISSUE TITLE
Click on the save of the plan box, how to save the content on the table displayed on the date

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#8]
![11](https://user-images.githubusercontent.com/34624856/51822988-ec2bee00-2318-11e9-921f-f2b5f2d74c00.png)

**Comment by sohee-lee7** [comment]
@xiaomao996688 When press save button, `onBeforeCreateSchedule` event occurs. In `onBeforeCreateSchedule` handler, a schedule of parameter should be pushed in `scheduleList`.

**Comment by xiaomao996688** [comment]
### 

> @xiaomao996688 When press save button, `onBeforeCreateSchedule` event occurs. In `onBeforeCreateSchedule` handler, a schedule of parameter should be pushed in `scheduleList`.

OnBeforeCreateSchedule is not triggered when you click Save
![image](https://user-images.githubusercontent.com/34624856/51876649-44f49880-23a4-11e9-9233-d8a698dbcdc8.png)

**Comment by sohee-lee7** [comment]
Did you register the event handler properly? like this:
![2019-01-29 10-07-54 993](https://user-images.githubusercontent.com/42666492/51877004-d288b600-23ad-11e9-81b4-1beeed29f5f6.png)

**Comment by xiaomao996688** [comment]
I registered to write an "on", thank you very much.

**Comment by xiaomao996688** [comment]
> Did you register the event handler properly? like this:
> ![2019-01-29 10-07-54 993](https://user-images.githubusercontent.com/42666492/51877004-d288b600-23ad-11e9-81b4-1beeed29f5f6.png)
I registered to write an "on", thank you very much.
