### ISSUE TITLE
How to use this method updateSchedule

### ISSUE THREAD

**Issue by xiaomao996688** [nhnent/toast-ui.vue-calendar#9]
How to use this method calendar.updateSchedule(schedule.id, schedule.calendarId, {
         Start: startTime,
         End: endTime
     });

**Comment by sohee-lee7** [comment]
You should use `invoke` for use method.
This link is how to use `invoke`.
https://github.com/nhnent/toast-ui.vue-calendar#method

**Comment by xiaomao996688** [comment]
> `invoke`

![image](https://user-images.githubusercontent.com/34624856/51951095-3a063a80-246e-11e9-8491-04367e1a9faf.png)
![image](https://user-images.githubusercontent.com/34624856/51951129-586c3600-246e-11e9-86f6-e0dcc6cd3f22.png)
![image](https://user-images.githubusercontent.com/34624856/51951155-6e79f680-246e-11e9-8b3e-5db1e3f50f61.png)
![image](https://user-images.githubusercontent.com/34624856/51951174-894c6b00-246e-11e9-85d6-f78cb054453c.png)
I use this method in this way does not work.

**Comment by sohee-lee7** [comment]
Try this code.
```js
this.$refs.tuiCal.invoke('updateSchedule', e.schedule.id, e.schedule.calendarId, e.schedule);
```
